import Foundation

enum LocalizedStrings {
    static func string(for key: LocalizedKey, tag: String) -> String {
        table[tag]?[key] ?? table["en"]?[key] ?? key.rawValue
    }

    private static let table: [String: [LocalizedKey: String]] = [
        "en": [
            .loginTitle: "Sign in to Pixiv",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "Log in",
            .loginProvisional: "Try without account",
            .tabRecommend: "Recommend",
            .tabDiscover: "Discover",
            .tabWhatsNew: "What's New",
            .homeNavTitle: "Home",
            .subRecommendedWorks: "Recommended works",
            .subPopularTags: "Popular Tags",
            .rankingTodayTitle: "Today's Ranking",
            .account: "Account",
            .actionDone: "Done",
            .actionLogOut: "Log out",
            .actionRefresh: "Refresh",
            .actionRetry: "Retry",
            .tokenTitle: "Token",
            .tokenAccess: "Access",
            .tokenExpiresFormat: "Expires %@",
            .nothingHere: "Nothing here yet",
        ],
        "zh-Hans": [
            .loginTitle: "登录 Pixiv",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "登录",
            .loginProvisional: "无账号体验",
            .tabRecommend: "推荐",
            .tabDiscover: "发现",
            .tabWhatsNew: "动态",
            .homeNavTitle: "首页",
            .subRecommendedWorks: "推荐作品",
            .subPopularTags: "热门标签",
            .rankingTodayTitle: "今日排行榜",
            .account: "账户",
            .actionDone: "完成",
            .actionLogOut: "退出登录",
            .actionRefresh: "刷新",
            .actionRetry: "重试",
            .tokenTitle: "令牌",
            .tokenAccess: "访问令牌",
            .tokenExpiresFormat: "%@ 过期",
            .nothingHere: "这里还没有内容",
        ],
        "zh-Hant": [
            .loginTitle: "登入 Pixiv",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "登入",
            .loginProvisional: "無帳號體驗",
            .tabRecommend: "推薦",
            .tabDiscover: "發現",
            .tabWhatsNew: "動態",
            .homeNavTitle: "首頁",
            .subRecommendedWorks: "推薦作品",
            .subPopularTags: "熱門標籤",
            .rankingTodayTitle: "今日排行榜",
            .account: "帳戶",
            .actionDone: "完成",
            .actionLogOut: "登出",
            .actionRefresh: "重新整理",
            .actionRetry: "重試",
            .tokenTitle: "權杖",
            .tokenAccess: "存取權杖",
            .tokenExpiresFormat: "%@ 失效",
            .nothingHere: "這裡還沒有內容",
        ],
        "ja": [
            .loginTitle: "Pixivにログイン",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "ログイン",
            .loginProvisional: "アカウントなしで試す",
            .tabRecommend: "おすすめ",
            .tabDiscover: "発見",
            .tabWhatsNew: "新着",
            .homeNavTitle: "ホーム",
            .subRecommendedWorks: "おすすめ",
            .subPopularTags: "人気のタグ",
            .rankingTodayTitle: "今日のランキング",
            .account: "アカウント",
            .actionDone: "完了",
            .actionLogOut: "ログアウト",
            .actionRefresh: "更新",
            .actionRetry: "再試行",
            .tokenTitle: "トークン",
            .tokenAccess: "アクセストークン",
            .tokenExpiresFormat: "%@ に失効",
            .nothingHere: "ここにはまだ何もありません",
        ],
        "ko": [
            .loginTitle: "Pixiv에 로그인",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "로그인",
            .loginProvisional: "계정 없이 시작",
            .tabRecommend: "추천",
            .tabDiscover: "탐색",
            .tabWhatsNew: "새 소식",
            .homeNavTitle: "홈 페이지",
            .subRecommendedWorks: "추천 작품",
            .subPopularTags: "인기 태그",
            .rankingTodayTitle: "오늘의 랭킹",
            .account: "계정",
            .actionDone: "완료",
            .actionLogOut: "로그아웃",
            .actionRefresh: "새로고침",
            .actionRetry: "재시도",
            .tokenTitle: "토큰",
            .tokenAccess: "액세스 토큰",
            .tokenExpiresFormat: "%@ 만료",
            .nothingHere: "아직 아무것도 없습니다",
        ],
        "ru": [
            .loginTitle: "Войти в Pixiv",
            .loginSubtitle: "OAuth 2.0 с PKCE",
            .loginAction: "Войти",
            .loginProvisional: "Попробовать без аккаунта",
            .tabRecommend: "Рекомендации",
            .tabDiscover: "Исследовать",
            .tabWhatsNew: "Новое",
            .homeNavTitle: "Первая страница",
            .subRecommendedWorks: "Рекомендуемые работы",
            .subPopularTags: "Популярные теги",
            .rankingTodayTitle: "Рейтинг за день",
            .account: "Аккаунт",
            .actionDone: "Готово",
            .actionLogOut: "Выйти",
            .actionRefresh: "Обновить",
            .actionRetry: "Повторить",
            .tokenTitle: "Токен",
            .tokenAccess: "Токен доступа",
            .tokenExpiresFormat: "Истекает %@",
            .nothingHere: "Здесь пока ничего нет",
        ],
        "tr": [
            .loginTitle: "Pixiv'e giriş yap",
            .loginSubtitle: "OAuth 2.0 PKCE ile",
            .loginAction: "Giriş yap",
            .loginProvisional: "Hesapsız dene",
            .tabRecommend: "Öneri",
            .tabDiscover: "Keşfet",
            .tabWhatsNew: "Yenilikler",
            .homeNavTitle: "Ana Sayfa",
            .subRecommendedWorks: "Önerilen eserler",
            .subPopularTags: "Popüler Etiketler",
            .rankingTodayTitle: "Günün Sıralaması",
            .account: "Hesap",
            .actionDone: "Tamam",
            .actionLogOut: "Çıkış yap",
            .actionRefresh: "Yenile",
            .actionRetry: "Yeniden dene",
            .tokenTitle: "Belirteç",
            .tokenAccess: "Erişim Belirteci",
            .tokenExpiresFormat: "Sona erme: %@",
            .nothingHere: "Henüz burada bir şey yok",
        ],
    ]
}
