import Foundation

enum LocalizedStrings {
    static func string(for key: LocalizedKey, tag: String) -> String {
        table[tag]?[key] ?? table["en"]?[key] ?? key.rawValue
    }

    private static let table: [String: [LocalizedKey: String]] = [
        "en": [
            .loginTitle: "Sign in to Pixiv",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "Log in",
            .loginProvisional: "Try without account",
            .tabRecommend: "Recommend",
            .tabDiscover: "Discover",
            .tabWhatsNew: "What's New",
            .homeNavTitle: "Home",
            .subRecommendedWorks: "Recommended works",
            .subPopularTags: "Popular Tags",
            .rankingTodayTitle: "Today's Ranking",
            .account: "Account",
            .actionDone: "Done",
            .actionLogOut: "Log out",
            .actionRefresh: "Refresh",
            .actionRetry: "Retry",
            .tokenTitle: "Token",
            .tokenAccess: "Access",
            .tokenExpiresFormat: "Expires %@",
            .nothingHere: "Nothing here yet",
            .detailRelated: "Related Works",
            .commentsTitle: "Comments",
            .viewAllComments: "View all comments",
            .commentsEmpty: "No comments yet",
            .novelRead: "Read",
            .profileIllusts: "Illusts",
            .profileManga: "Manga",
            .profileNovels: "Novels",
            .profileBookmarks: "Bookmarks",
            .profileFollow: "Follow",
            .profileFollowing: "Following",
            .searchTitle: "Search",
            .searchPlaceholder: "Search Pixiv",
            .searchTabIllust: "Illusts",
            .searchTabNovel: "Novels",
            .searchTabUser: "Users",
            .rankingTitle: "Ranking",
            .rankModeDay: "Daily",
            .rankModeWeek: "Weekly",
            .rankModeMonth: "Monthly",
            .rankModeDayMale: "Daily (Male)",
            .rankModeDayFemale: "Daily (Female)",
            .rankModeWeekRookie: "Weekly Rookie",
            .rankModeWeekOriginal: "Weekly Original",
            .rankModeDayManga: "Daily Manga",
            .discoverSpotlight: "Spotlight",
            .moreTitle: "More",
            .historyTitle: "History",
            .historyAll: "All",
            .downloadsTitle: "Downloads",
            .mutedTitle: "Muted",
            .settingsTitle: "Settings",
            .aboutTitle: "About",
            .settingsLanguage: "Language",
            .settingsContent: "Content",
            .settingsHideR18: "Hide R-18",
            .settingsColumns: "Columns",
            .settingsNetwork: "Network",
            .settingsDirectConnect: "Direct connect (Cronet)",
            .commentCompose: "Write a comment",
            .latestWorksTitle: "Latest Works",
            .recommendUsersTitle: "Recommended Users",
            .userRelatedTitle: "Related Users",
            .userIllustSeriesTitle: "Illust Series",
            .userNovelSeriesTitle: "Novel Series",
            .searchDurationAll: "Any time",
            .searchDurationDay: "Past day",
            .searchDurationWeek: "Past week",
            .searchDurationMonth: "Past month",
            .muteUsers: "Users",
            .muteTags: "Tags",
            .muteAddTag: "Add a tag",
            .searchSortDateDesc: "Newest",
            .searchSortDateAsc: "Oldest",
            .searchSortPopular: "Popular",
            .searchSortLabel: "Sort",
            .followingPublic: "Public",
            .followingPrivate: "Private",
            .followingMyPixiv: "MyPixiv",
            .seriesTitle: "Series",
            .bookmarkPublic: "Add to public",
            .bookmarkPrivate: "Add to private",
            .bookmarkAction: "Bookmark",
            .bookmarkRestrictTitle: "Bookmark visibility",
            .commentReply: "Reply",
            .commentShowReplies: "Show replies",
            .commentHideReplies: "Hide replies",
            .actionShare: "Share",
            .actionCopyLink: "Copy link",
            .actionOpenInBrowser: "Open in browser",
            .actionMuteArtist: "Mute artist",
            .actionMuteUser: "Mute user",
            .actionUnmuteUser: "Unmute user",
            .bookmarkTagsTitle: "Tags",
            .bookmarkTagsPlaceholder: "Comma-separated tags",
            .bookmarkTagsSuggested: "From this work",
            .bookmarkWithTags: "Bookmark with tags…",
            .bookmarkTagAll: "All",
            .actionCancel: "Cancel",
            .searchTargetPartial: "Tags (partial)",
            .searchTargetExact: "Tags (exact)",
            .searchTargetTitleCaption: "Title & caption",
            .searchOpenLink: "Open link",
            .searchRecent: "Recent",
            .actionClear: "Clear",
        ],
        "zh-Hans": [
            .loginTitle: "登录 Pixiv",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "登录",
            .loginProvisional: "无账号体验",
            .tabRecommend: "推荐",
            .tabDiscover: "发现",
            .tabWhatsNew: "动态",
            .homeNavTitle: "首页",
            .subRecommendedWorks: "推荐作品",
            .subPopularTags: "热门标签",
            .rankingTodayTitle: "今日排行榜",
            .account: "账户",
            .actionDone: "完成",
            .actionLogOut: "退出登录",
            .actionRefresh: "刷新",
            .actionRetry: "重试",
            .tokenTitle: "令牌",
            .tokenAccess: "访问令牌",
            .tokenExpiresFormat: "%@ 过期",
            .nothingHere: "这里还没有内容",
            .detailRelated: "相关作品",
            .commentsTitle: "评论",
            .viewAllComments: "查看全部评论",
            .commentsEmpty: "暂无评论",
            .novelRead: "阅读",
            .profileIllusts: "插画",
            .profileManga: "漫画",
            .profileNovels: "小说",
            .profileBookmarks: "收藏",
            .profileFollow: "关注",
            .profileFollowing: "已关注",
            .searchTitle: "搜索",
            .searchPlaceholder: "搜索 Pixiv",
            .searchTabIllust: "插画",
            .searchTabNovel: "小说",
            .searchTabUser: "用户",
            .rankingTitle: "排行榜",
            .rankModeDay: "日榜",
            .rankModeWeek: "周榜",
            .rankModeMonth: "月榜",
            .rankModeDayMale: "男性向日榜",
            .rankModeDayFemale: "女性向日榜",
            .rankModeWeekRookie: "新人周榜",
            .rankModeWeekOriginal: "原创周榜",
            .rankModeDayManga: "漫画日榜",
            .discoverSpotlight: "特辑",
            .moreTitle: "更多",
            .historyTitle: "历史记录",
            .historyAll: "全部",
            .downloadsTitle: "下载",
            .mutedTitle: "屏蔽",
            .settingsTitle: "设置",
            .aboutTitle: "关于",
            .settingsLanguage: "语言",
            .settingsContent: "内容",
            .settingsHideR18: "隐藏 R-18",
            .settingsColumns: "列数",
            .settingsNetwork: "网络",
            .settingsDirectConnect: "直连模式（Cronet）",
            .commentCompose: "写评论",
            .latestWorksTitle: "最新作品",
            .recommendUsersTitle: "推荐用户",
            .userRelatedTitle: "相关用户",
            .userIllustSeriesTitle: "插画系列",
            .userNovelSeriesTitle: "小说系列",
            .searchDurationAll: "全部时间",
            .searchDurationDay: "最近一天",
            .searchDurationWeek: "最近一周",
            .searchDurationMonth: "最近一月",
            .muteUsers: "用户",
            .muteTags: "标签",
            .muteAddTag: "添加标签",
            .searchSortDateDesc: "最新",
            .searchSortDateAsc: "最旧",
            .searchSortPopular: "热度",
            .searchSortLabel: "排序",
            .followingPublic: "公开",
            .followingPrivate: "私密",
            .followingMyPixiv: "好P友",
            .seriesTitle: "系列",
            .bookmarkPublic: "公开收藏",
            .bookmarkPrivate: "私密收藏",
            .bookmarkAction: "收藏",
            .bookmarkRestrictTitle: "收藏可见性",
            .commentReply: "回复",
            .commentShowReplies: "查看回复",
            .commentHideReplies: "收起回复",
            .actionShare: "分享",
            .actionCopyLink: "复制链接",
            .actionOpenInBrowser: "在浏览器中打开",
            .actionMuteArtist: "屏蔽作者",
            .actionMuteUser: "屏蔽用户",
            .actionUnmuteUser: "取消屏蔽",
            .bookmarkTagsTitle: "标签",
            .bookmarkTagsPlaceholder: "用逗号分隔标签",
            .bookmarkTagsSuggested: "作品标签",
            .bookmarkWithTags: "添加标签后收藏…",
            .bookmarkTagAll: "全部",
            .actionCancel: "取消",
            .searchTargetPartial: "标签（部分）",
            .searchTargetExact: "标签（精确）",
            .searchTargetTitleCaption: "标题与简介",
            .searchOpenLink: "打开链接",
            .searchRecent: "最近搜索",
            .actionClear: "清空",
        ],
        "zh-Hant": [
            .loginTitle: "登入 Pixiv",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "登入",
            .loginProvisional: "無帳號體驗",
            .tabRecommend: "推薦",
            .tabDiscover: "發現",
            .tabWhatsNew: "動態",
            .homeNavTitle: "首頁",
            .subRecommendedWorks: "推薦作品",
            .subPopularTags: "熱門標籤",
            .rankingTodayTitle: "今日排行榜",
            .account: "帳戶",
            .actionDone: "完成",
            .actionLogOut: "登出",
            .actionRefresh: "重新整理",
            .actionRetry: "重試",
            .tokenTitle: "權杖",
            .tokenAccess: "存取權杖",
            .tokenExpiresFormat: "%@ 失效",
            .nothingHere: "這裡還沒有內容",
            .detailRelated: "相關作品",
            .commentsTitle: "評論",
            .viewAllComments: "查看全部評論",
            .commentsEmpty: "暫無評論",
            .novelRead: "閱讀",
            .profileIllusts: "插畫",
            .profileManga: "漫畫",
            .profileNovels: "小說",
            .profileBookmarks: "收藏",
            .profileFollow: "關注",
            .profileFollowing: "已關注",
            .searchTitle: "搜尋",
            .searchPlaceholder: "搜尋 Pixiv",
            .searchTabIllust: "插畫",
            .searchTabNovel: "小說",
            .searchTabUser: "使用者",
            .rankingTitle: "排行榜",
            .rankModeDay: "日榜",
            .rankModeWeek: "週榜",
            .rankModeMonth: "月榜",
            .rankModeDayMale: "男性向日榜",
            .rankModeDayFemale: "女性向日榜",
            .rankModeWeekRookie: "新人週榜",
            .rankModeWeekOriginal: "原創週榜",
            .rankModeDayManga: "漫畫日榜",
            .discoverSpotlight: "特輯",
            .moreTitle: "更多",
            .historyTitle: "歷史記錄",
            .historyAll: "全部",
            .downloadsTitle: "下載",
            .mutedTitle: "封鎖",
            .settingsTitle: "設定",
            .aboutTitle: "關於",
            .settingsLanguage: "語言",
            .settingsContent: "內容",
            .settingsHideR18: "隱藏 R-18",
            .settingsColumns: "欄數",
            .settingsNetwork: "網路",
            .settingsDirectConnect: "直連模式（Cronet）",
            .commentCompose: "寫評論",
            .latestWorksTitle: "最新作品",
            .recommendUsersTitle: "推薦使用者",
            .userRelatedTitle: "相關使用者",
            .userIllustSeriesTitle: "插畫系列",
            .userNovelSeriesTitle: "小說系列",
            .searchDurationAll: "全部時間",
            .searchDurationDay: "最近一天",
            .searchDurationWeek: "最近一週",
            .searchDurationMonth: "最近一月",
            .muteUsers: "使用者",
            .muteTags: "標籤",
            .muteAddTag: "新增標籤",
            .searchSortDateDesc: "最新",
            .searchSortDateAsc: "最舊",
            .searchSortPopular: "熱度",
            .searchSortLabel: "排序",
            .followingPublic: "公開",
            .followingPrivate: "私密",
            .followingMyPixiv: "好P友",
            .seriesTitle: "系列",
            .bookmarkPublic: "公開收藏",
            .bookmarkPrivate: "私密收藏",
            .bookmarkAction: "收藏",
            .bookmarkRestrictTitle: "收藏可見性",
            .commentReply: "回覆",
            .commentShowReplies: "查看回覆",
            .commentHideReplies: "收起回覆",
            .actionShare: "分享",
            .actionCopyLink: "複製連結",
            .actionOpenInBrowser: "用瀏覽器開啟",
            .actionMuteArtist: "封鎖作者",
            .actionMuteUser: "封鎖使用者",
            .actionUnmuteUser: "取消封鎖",
            .bookmarkTagsTitle: "標籤",
            .bookmarkTagsPlaceholder: "以逗號分隔標籤",
            .bookmarkTagsSuggested: "作品標籤",
            .bookmarkWithTags: "加標籤後收藏…",
            .bookmarkTagAll: "全部",
            .actionCancel: "取消",
            .searchTargetPartial: "標籤（部分）",
            .searchTargetExact: "標籤（精確）",
            .searchTargetTitleCaption: "標題與簡介",
            .searchOpenLink: "開啟連結",
            .searchRecent: "最近搜尋",
            .actionClear: "清空",
        ],
        "ja": [
            .loginTitle: "Pixivにログイン",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "ログイン",
            .loginProvisional: "アカウントなしで試す",
            .tabRecommend: "おすすめ",
            .tabDiscover: "発見",
            .tabWhatsNew: "新着",
            .homeNavTitle: "ホーム",
            .subRecommendedWorks: "おすすめ",
            .subPopularTags: "人気のタグ",
            .rankingTodayTitle: "今日のランキング",
            .account: "アカウント",
            .actionDone: "完了",
            .actionLogOut: "ログアウト",
            .actionRefresh: "更新",
            .actionRetry: "再試行",
            .tokenTitle: "トークン",
            .tokenAccess: "アクセストークン",
            .tokenExpiresFormat: "%@ に失効",
            .nothingHere: "ここにはまだ何もありません",
            .detailRelated: "関連作品",
            .commentsTitle: "コメント",
            .viewAllComments: "すべてのコメントを見る",
            .commentsEmpty: "コメントはまだありません",
            .novelRead: "読む",
            .profileIllusts: "イラスト",
            .profileManga: "マンガ",
            .profileNovels: "小説",
            .profileBookmarks: "ブックマーク",
            .profileFollow: "フォロー",
            .profileFollowing: "フォロー中",
            .searchTitle: "検索",
            .searchPlaceholder: "Pixiv を検索",
            .searchTabIllust: "イラスト",
            .searchTabNovel: "小説",
            .searchTabUser: "ユーザー",
            .rankingTitle: "ランキング",
            .rankModeDay: "デイリー",
            .rankModeWeek: "ウィークリー",
            .rankModeMonth: "マンスリー",
            .rankModeDayMale: "男性向けデイリー",
            .rankModeDayFemale: "女性向けデイリー",
            .rankModeWeekRookie: "新人ウィークリー",
            .rankModeWeekOriginal: "オリジナルウィークリー",
            .rankModeDayManga: "マンガデイリー",
            .discoverSpotlight: "特集",
            .moreTitle: "その他",
            .historyTitle: "履歴",
            .historyAll: "すべて",
            .downloadsTitle: "ダウンロード",
            .mutedTitle: "ミュート",
            .settingsTitle: "設定",
            .aboutTitle: "概要",
            .settingsLanguage: "言語",
            .settingsContent: "コンテンツ",
            .settingsHideR18: "R-18 を非表示",
            .settingsColumns: "列数",
            .settingsNetwork: "ネットワーク",
            .settingsDirectConnect: "直接接続（Cronet）",
            .commentCompose: "コメントを書く",
            .latestWorksTitle: "最新の作品",
            .recommendUsersTitle: "おすすめユーザー",
            .userRelatedTitle: "関連ユーザー",
            .userIllustSeriesTitle: "イラストシリーズ",
            .userNovelSeriesTitle: "小説シリーズ",
            .searchDurationAll: "すべての期間",
            .searchDurationDay: "24時間以内",
            .searchDurationWeek: "1週間以内",
            .searchDurationMonth: "1か月以内",
            .muteUsers: "ユーザー",
            .muteTags: "タグ",
            .muteAddTag: "タグを追加",
            .searchSortDateDesc: "新しい順",
            .searchSortDateAsc: "古い順",
            .searchSortPopular: "人気",
            .searchSortLabel: "並べ替え",
            .followingPublic: "公開",
            .followingPrivate: "非公開",
            .followingMyPixiv: "マイピク",
            .seriesTitle: "シリーズ",
            .bookmarkPublic: "公開ブックマーク",
            .bookmarkPrivate: "非公開ブックマーク",
            .bookmarkAction: "ブックマーク",
            .bookmarkRestrictTitle: "ブックマークの公開設定",
            .commentReply: "返信",
            .commentShowReplies: "返信を表示",
            .commentHideReplies: "返信を隠す",
            .actionShare: "シェア",
            .actionCopyLink: "リンクをコピー",
            .actionOpenInBrowser: "ブラウザで開く",
            .actionMuteArtist: "作者をミュート",
            .actionMuteUser: "ユーザーをミュート",
            .actionUnmuteUser: "ミュートを解除",
            .bookmarkTagsTitle: "タグ",
            .bookmarkTagsPlaceholder: "カンマ区切りのタグ",
            .bookmarkTagsSuggested: "作品のタグ",
            .bookmarkWithTags: "タグを付けてブックマーク…",
            .bookmarkTagAll: "すべて",
            .actionCancel: "キャンセル",
            .searchTargetPartial: "タグ（部分一致）",
            .searchTargetExact: "タグ（完全一致）",
            .searchTargetTitleCaption: "タイトル・キャプション",
            .searchOpenLink: "リンクを開く",
            .searchRecent: "履歴",
            .actionClear: "消去",
        ],
        "ko": [
            .loginTitle: "Pixiv에 로그인",
            .loginSubtitle: "OAuth 2.0 with PKCE",
            .loginAction: "로그인",
            .loginProvisional: "계정 없이 시작",
            .tabRecommend: "추천",
            .tabDiscover: "탐색",
            .tabWhatsNew: "새 소식",
            .homeNavTitle: "홈 페이지",
            .subRecommendedWorks: "추천 작품",
            .subPopularTags: "인기 태그",
            .rankingTodayTitle: "오늘의 랭킹",
            .account: "계정",
            .actionDone: "완료",
            .actionLogOut: "로그아웃",
            .actionRefresh: "새로고침",
            .actionRetry: "재시도",
            .tokenTitle: "토큰",
            .tokenAccess: "액세스 토큰",
            .tokenExpiresFormat: "%@ 만료",
            .nothingHere: "아직 아무것도 없습니다",
            .detailRelated: "관련 작품",
            .commentsTitle: "댓글",
            .viewAllComments: "모든 댓글 보기",
            .commentsEmpty: "댓글이 없습니다",
            .novelRead: "읽기",
            .profileIllusts: "일러스트",
            .profileManga: "만화",
            .profileNovels: "소설",
            .profileBookmarks: "북마크",
            .profileFollow: "팔로우",
            .profileFollowing: "팔로잉",
            .searchTitle: "검색",
            .searchPlaceholder: "Pixiv 검색",
            .searchTabIllust: "일러스트",
            .searchTabNovel: "소설",
            .searchTabUser: "사용자",
            .rankingTitle: "랭킹",
            .rankModeDay: "일간",
            .rankModeWeek: "주간",
            .rankModeMonth: "월간",
            .rankModeDayMale: "남성 일간",
            .rankModeDayFemale: "여성 일간",
            .rankModeWeekRookie: "신인 주간",
            .rankModeWeekOriginal: "오리지널 주간",
            .rankModeDayManga: "만화 일간",
            .discoverSpotlight: "특집",
            .moreTitle: "더 보기",
            .historyTitle: "기록",
            .historyAll: "전체",
            .downloadsTitle: "다운로드",
            .mutedTitle: "차단",
            .settingsTitle: "설정",
            .aboutTitle: "정보",
            .settingsLanguage: "언어",
            .settingsContent: "콘텐츠",
            .settingsHideR18: "R-18 숨기기",
            .settingsColumns: "열 수",
            .settingsNetwork: "네트워크",
            .settingsDirectConnect: "직접 연결 (Cronet)",
            .commentCompose: "댓글 쓰기",
            .latestWorksTitle: "최신 작품",
            .recommendUsersTitle: "추천 사용자",
            .userRelatedTitle: "관련 사용자",
            .userIllustSeriesTitle: "일러스트 시리즈",
            .userNovelSeriesTitle: "소설 시리즈",
            .searchDurationAll: "전체 기간",
            .searchDurationDay: "최근 하루",
            .searchDurationWeek: "최근 일주일",
            .searchDurationMonth: "최근 한 달",
            .muteUsers: "사용자",
            .muteTags: "태그",
            .muteAddTag: "태그 추가",
            .searchSortDateDesc: "최신순",
            .searchSortDateAsc: "오래된순",
            .searchSortPopular: "인기순",
            .searchSortLabel: "정렬",
            .followingPublic: "공개",
            .followingPrivate: "비공개",
            .followingMyPixiv: "MyPixiv",
            .seriesTitle: "시리즈",
            .bookmarkPublic: "공개 북마크",
            .bookmarkPrivate: "비공개 북마크",
            .bookmarkAction: "북마크",
            .bookmarkRestrictTitle: "북마크 공개 설정",
            .commentReply: "답글",
            .commentShowReplies: "답글 보기",
            .commentHideReplies: "답글 숨기기",
            .actionShare: "공유",
            .actionCopyLink: "링크 복사",
            .actionOpenInBrowser: "브라우저에서 열기",
            .actionMuteArtist: "작가 차단",
            .actionMuteUser: "사용자 차단",
            .actionUnmuteUser: "차단 해제",
            .bookmarkTagsTitle: "태그",
            .bookmarkTagsPlaceholder: "쉼표로 구분된 태그",
            .bookmarkTagsSuggested: "작품 태그",
            .bookmarkWithTags: "태그 추가하여 북마크…",
            .bookmarkTagAll: "전체",
            .actionCancel: "취소",
            .searchTargetPartial: "태그(부분 일치)",
            .searchTargetExact: "태그(정확히 일치)",
            .searchTargetTitleCaption: "제목・설명",
            .searchOpenLink: "링크 열기",
            .searchRecent: "최근 검색",
            .actionClear: "지우기",
        ],
        "ru": [
            .loginTitle: "Войти в Pixiv",
            .loginSubtitle: "OAuth 2.0 с PKCE",
            .loginAction: "Войти",
            .loginProvisional: "Попробовать без аккаунта",
            .tabRecommend: "Рекомендации",
            .tabDiscover: "Исследовать",
            .tabWhatsNew: "Новое",
            .homeNavTitle: "Первая страница",
            .subRecommendedWorks: "Рекомендуемые работы",
            .subPopularTags: "Популярные теги",
            .rankingTodayTitle: "Рейтинг за день",
            .account: "Аккаунт",
            .actionDone: "Готово",
            .actionLogOut: "Выйти",
            .actionRefresh: "Обновить",
            .actionRetry: "Повторить",
            .tokenTitle: "Токен",
            .tokenAccess: "Токен доступа",
            .tokenExpiresFormat: "Истекает %@",
            .nothingHere: "Здесь пока ничего нет",
            .detailRelated: "Похожие работы",
            .commentsTitle: "Комментарии",
            .viewAllComments: "Все комментарии",
            .commentsEmpty: "Нет комментариев",
            .novelRead: "Читать",
            .profileIllusts: "Иллюстрации",
            .profileManga: "Манга",
            .profileNovels: "Новеллы",
            .profileBookmarks: "Закладки",
            .profileFollow: "Подписаться",
            .profileFollowing: "Вы подписаны",
            .searchTitle: "Поиск",
            .searchPlaceholder: "Поиск Pixiv",
            .searchTabIllust: "Иллюстрации",
            .searchTabNovel: "Новеллы",
            .searchTabUser: "Пользователи",
            .rankingTitle: "Рейтинг",
            .rankModeDay: "День",
            .rankModeWeek: "Неделя",
            .rankModeMonth: "Месяц",
            .rankModeDayMale: "День (М)",
            .rankModeDayFemale: "День (Ж)",
            .rankModeWeekRookie: "Новички",
            .rankModeWeekOriginal: "Оригинал",
            .rankModeDayManga: "Манга / День",
            .discoverSpotlight: "Подборка",
            .moreTitle: "Ещё",
            .historyTitle: "История",
            .historyAll: "Все",
            .downloadsTitle: "Загрузки",
            .mutedTitle: "Скрытые",
            .settingsTitle: "Настройки",
            .aboutTitle: "О приложении",
            .settingsLanguage: "Язык",
            .settingsContent: "Контент",
            .settingsHideR18: "Скрыть R-18",
            .settingsColumns: "Столбцы",
            .settingsNetwork: "Сеть",
            .settingsDirectConnect: "Прямое соединение (Cronet)",
            .commentCompose: "Написать комментарий",
            .latestWorksTitle: "Новые работы",
            .recommendUsersTitle: "Рекомендуемые пользователи",
            .userRelatedTitle: "Похожие авторы",
            .userIllustSeriesTitle: "Серии иллюстраций",
            .userNovelSeriesTitle: "Серии новелл",
            .searchDurationAll: "За всё время",
            .searchDurationDay: "За день",
            .searchDurationWeek: "За неделю",
            .searchDurationMonth: "За месяц",
            .muteUsers: "Пользователи",
            .muteTags: "Теги",
            .muteAddTag: "Добавить тег",
            .searchSortDateDesc: "Новые",
            .searchSortDateAsc: "Старые",
            .searchSortPopular: "Популярные",
            .searchSortLabel: "Сортировка",
            .followingPublic: "Публично",
            .followingPrivate: "Скрытые",
            .followingMyPixiv: "MyPixiv",
            .seriesTitle: "Серия",
            .bookmarkPublic: "Публичная закладка",
            .bookmarkPrivate: "Скрытая закладка",
            .bookmarkAction: "Закладка",
            .bookmarkRestrictTitle: "Видимость закладки",
            .commentReply: "Ответить",
            .commentShowReplies: "Показать ответы",
            .commentHideReplies: "Скрыть ответы",
            .actionShare: "Поделиться",
            .actionCopyLink: "Скопировать ссылку",
            .actionOpenInBrowser: "Открыть в браузере",
            .actionMuteArtist: "Скрыть автора",
            .actionMuteUser: "Скрыть пользователя",
            .actionUnmuteUser: "Снять скрытие",
            .bookmarkTagsTitle: "Теги",
            .bookmarkTagsPlaceholder: "Теги через запятую",
            .bookmarkTagsSuggested: "Теги работы",
            .bookmarkWithTags: "Закладка с тегами…",
            .bookmarkTagAll: "Все",
            .actionCancel: "Отмена",
            .searchTargetPartial: "Теги (частично)",
            .searchTargetExact: "Теги (точно)",
            .searchTargetTitleCaption: "Название и описание",
            .searchOpenLink: "Открыть ссылку",
            .searchRecent: "Недавние",
            .actionClear: "Очистить",
        ],
        "tr": [
            .loginTitle: "Pixiv'e giriş yap",
            .loginSubtitle: "OAuth 2.0 PKCE ile",
            .loginAction: "Giriş yap",
            .loginProvisional: "Hesapsız dene",
            .tabRecommend: "Öneri",
            .tabDiscover: "Keşfet",
            .tabWhatsNew: "Yenilikler",
            .homeNavTitle: "Ana Sayfa",
            .subRecommendedWorks: "Önerilen eserler",
            .subPopularTags: "Popüler Etiketler",
            .rankingTodayTitle: "Günün Sıralaması",
            .account: "Hesap",
            .actionDone: "Tamam",
            .actionLogOut: "Çıkış yap",
            .actionRefresh: "Yenile",
            .actionRetry: "Yeniden dene",
            .tokenTitle: "Belirteç",
            .tokenAccess: "Erişim Belirteci",
            .tokenExpiresFormat: "Sona erme: %@",
            .nothingHere: "Henüz burada bir şey yok",
            .detailRelated: "İlgili Eserler",
            .commentsTitle: "Yorumlar",
            .viewAllComments: "Tüm yorumları gör",
            .commentsEmpty: "Henüz yorum yok",
            .novelRead: "Oku",
            .profileIllusts: "Çizimler",
            .profileManga: "Manga",
            .profileNovels: "Romanlar",
            .profileBookmarks: "Yer İmleri",
            .profileFollow: "Takip et",
            .profileFollowing: "Takip ediliyor",
            .searchTitle: "Ara",
            .searchPlaceholder: "Pixiv'de ara",
            .searchTabIllust: "Çizimler",
            .searchTabNovel: "Romanlar",
            .searchTabUser: "Kullanıcılar",
            .rankingTitle: "Sıralama",
            .rankModeDay: "Günlük",
            .rankModeWeek: "Haftalık",
            .rankModeMonth: "Aylık",
            .rankModeDayMale: "Günlük (Erkek)",
            .rankModeDayFemale: "Günlük (Kadın)",
            .rankModeWeekRookie: "Haftalık Yeni",
            .rankModeWeekOriginal: "Haftalık Özgün",
            .rankModeDayManga: "Günlük Manga",
            .discoverSpotlight: "Öne Çıkanlar",
            .moreTitle: "Daha Fazla",
            .historyTitle: "Geçmiş",
            .historyAll: "Hepsi",
            .downloadsTitle: "İndirilenler",
            .mutedTitle: "Sessize Alınan",
            .settingsTitle: "Ayarlar",
            .aboutTitle: "Hakkında",
            .settingsLanguage: "Dil",
            .settingsContent: "İçerik",
            .settingsHideR18: "R-18'i gizle",
            .settingsColumns: "Sütun sayısı",
            .settingsNetwork: "Ağ",
            .settingsDirectConnect: "Doğrudan bağlantı (Cronet)",
            .commentCompose: "Yorum yaz",
            .latestWorksTitle: "Yeni Eserler",
            .recommendUsersTitle: "Önerilen Kullanıcılar",
            .userRelatedTitle: "İlgili Kullanıcılar",
            .userIllustSeriesTitle: "Çizim Serileri",
            .userNovelSeriesTitle: "Roman Serileri",
            .searchDurationAll: "Her zaman",
            .searchDurationDay: "Son gün",
            .searchDurationWeek: "Son hafta",
            .searchDurationMonth: "Son ay",
            .muteUsers: "Kullanıcılar",
            .muteTags: "Etiketler",
            .muteAddTag: "Etiket ekle",
            .searchSortDateDesc: "Yeni",
            .searchSortDateAsc: "Eski",
            .searchSortPopular: "Popüler",
            .searchSortLabel: "Sırala",
            .followingPublic: "Herkese açık",
            .followingPrivate: "Gizli",
            .followingMyPixiv: "MyPixiv",
            .seriesTitle: "Seri",
            .bookmarkPublic: "Genel yer imi",
            .bookmarkPrivate: "Özel yer imi",
            .bookmarkAction: "Yer İmi",
            .bookmarkRestrictTitle: "Yer imi görünürlüğü",
            .commentReply: "Yanıtla",
            .commentShowReplies: "Yanıtları göster",
            .commentHideReplies: "Yanıtları gizle",
            .actionShare: "Paylaş",
            .actionCopyLink: "Bağlantıyı kopyala",
            .actionOpenInBrowser: "Tarayıcıda aç",
            .actionMuteArtist: "Sanatçıyı sustur",
            .actionMuteUser: "Kullanıcıyı sustur",
            .actionUnmuteUser: "Sustırmayı kaldır",
            .bookmarkTagsTitle: "Etiketler",
            .bookmarkTagsPlaceholder: "Virgülle ayrılmış etiketler",
            .bookmarkTagsSuggested: "Eserin etiketleri",
            .bookmarkWithTags: "Etiketle yer imine ekle…",
            .bookmarkTagAll: "Hepsi",
            .actionCancel: "İptal",
            .searchTargetPartial: "Etiket (kısmi)",
            .searchTargetExact: "Etiket (tam)",
            .searchTargetTitleCaption: "Başlık ve açıklama",
            .searchOpenLink: "Bağlantıyı aç",
            .searchRecent: "Son aramalar",
            .actionClear: "Temizle",
        ],
    ]
}
